### PR TITLE
Exception handling

### PR DESCRIPTION
**Pull request by DataWorm**
Hi,

I'm finally back and made sure I can spend a little bit of time in this project. I also just realised the contributor changes in the pom file while working on it, thx! ;-)

I made a first implementation with exception handling. You mentioned some result object containing all the needed information but as I haven't seen any advantage in that approach I just tried it directly with some RuntimeExceptions. Please tell me if I missed something or if you think there is a cleaner solution.

I also wondered about the updateQuery implementation. You assume that the request succeeds and only in case of a 204 you assume that it failed. I haven't checked yet for the usual behaviour in case of a succeeded/failed update query but I guess there is also some space for improvement. Maybe I can work it out tomorrow but I can't access an octoprint instance atm.

slf4j is added as dependency but I haven't used it yet. Depending on time I might look through the code soon and replace stacktraces with logs or even with better exception handling but probably we just have to add these things step by step. ;-)

### CODE REVIEW

**Comment by robweber** [comment]
I think this method works well; it throws the error but in a way that won't result in the whole thing crashing for the user, or requiring them to having tons of try/catch blocks in their own code. 

I like the addition of the slf4j dependency. Initially the library was simple enough that I didn't include a lot of logging code, other than some print statements when testing. It's to the point now that going through and getting some unified logging would be of benefit; especially with the errors. I think going through and doing that after the basic exceptions make sense. 

Regarding the ```executeUpdate()``` method you're correct, there is room for improvement here. I think you might have the code backwards though in adapting it from how my method worked. If you __don't__ get the 204 error the request has failed. 204 is the success condition. Looks like yours will return false in that case. There are other errors depending on the operation (such as a 409 for a[ job operation](http://docs.octoprint.org/en/master/api/job.html#issue-a-job-command)), but it looks like your generic ```OctoPrintAPIAPIException``` would catch these. It can always be further extended for specific errors if we wanted to take the time for that. I think the generic success status is 200 though, not 400. 

I made a quick change to your ```handleConnection()``` method to take the status condition as an int argument. I think that could work for modifying what you have to handle both the default condition (200) and the update condition (204) without a lot of modifications. If you don't like it feel free to do something different, lots of ways to accomplish the same thing. 

[Handle Connection Arg Addition](https://github.com/robweber/octoprint-java-lib/commit/e4fe168b84f740a7098de1889820280916c38dde)

**Comment by DataWorm** [comment]
Yep as useful I am fine with your changes. 
As you mentioned the exceptions can be extended or will be collected as a general exception. I am not sure if there might be some api methods that return the same status code for a different kind of failure. Therefore I haven't tried yet to define an exception class for every mentioned status code. The command classes could still wrap these general exceptions in new exceptions and provide more details regarding that status code if needed.

**Comment by robweber** [comment]
Sounds like a plan. The documentation is pretty good about giving info on what error codes to expect for methods. We'd have to go through each one and find common codes and such, that's a project for later. 

I'm going to do some real life testing on my OctoPrint server with the exceptions branch just to verify functionality before merging.

**Comment by DataWorm** [comment]
I already validated the specific errors like no connection possible or invalid api key, both worked just fine.

**Pull request merged**
