### PR TITLE
Pausing job actions

### PR DESCRIPTION
**Pull request by DataWorm**
Api was extended to allow further types of pause commands for print jobs.

### CODE REVIEW

**Comment by robweber** [comment]
Wow they sure made the API interesting on that one, had to re-read their docs to even understand why you'd need to set it up that way. 

2 suggestions. Can you make them all 1 word enum values like "RESUME" and "TOGGLE" instead of "PAUSE_TOGGLE". From an end-user perspective Toggle should be enough to understand what it's doing without knowing that under the hood it's really doing command: pause, action: toggle. I'm thinking you should be able to use the library without having to read the Octoprint docs to understand why it's called PAUSE_TOGGLE. 

The other suggestion is to have just one PAUSE command. From the looks of the documentation the "pause" command with no action is the same as the "pause" command with the "toggle" action. That is kind of confusing to me so just combining them so we always know what action the value will take makes more sense to me. In the end we'd have 

```
START,
CANCEL,
RESTART,
PAUSE,
TOGGLE,
RESUME

```

**Comment by DataWorm** [comment]
Yeah sure that's fine for me, will be done in 5 minutes! I've chosen that solution for backward compatibility. With the new name suggestions the pause behaviour is going to change from toggle to just pause but I guess the probably small amount of library users and the change of version number shouldn't result in too much confusion. :-D

**Comment by DataWorm** [comment]
done!

**Comment by robweber** [comment]
Thanks!

Yea you're probably right about that. The small amount of users can deal with a breaking change on this one. I know my uses won't suffer too much!

**Pull request merged**
