### PR TITLE
Settings map

### PR DESCRIPTION
**Pull request by DataWorm**
Okay as offered here is an implementation that offers all settings as a flat map. Advantage regarding the existing method is that people don't have to handle with json objects and can directly access any setting without traversing a tree.

### CODE REVIEW

**Comment by robweber** [comment]
Looks good, now that I see it implemented I can see how this is easier than going through the JSONObject. 

Before merging in wondering if the getAllSettings method should now be renamed getSettingsJson() or something like that? I think it's useful to keep that method public as you may sometimes want the entire JSON structure, especially if someone wants to make their own POJO. Also, would you mind moving the private method to just under the constructor? Code-wise I find it helpful to see the constructors, private, protected, and then public methods in that order (sorry, I know it's just a preference but keeps things consistent). 

Thanks again for your efforts with this project!

**Comment by DataWorm** [comment]
Yeah I'm fine with these things, feel free to rename the methods or change the order in whatever way you prefer it! =)

**Comment by robweber** [comment]
Before I merge it in do you have any thoughts on the handeling of arrays in the settings? I noticed that same settings values return arrays. The flat map code converts these to strings so you end up with something like 
```
"terminalFilters" = [{"regex":"(Send: (N\\d+\\s+)?M105)|(Recv: ok (B|T\\d*):)","name":"Suppress temperature messages"}, ..... ]

```
I guess I'm on the fence on if this should be modified or if it doesn't matter 99% of the time. You could go through the array and end up with something like: 

```
"terminalFilters.1.regex" = "(Send: (N\\d+\\s+)?M105)|(Recv: ok (B|T\\d*):)"
"terminalFilters.1.name" = "Suppress temperature messages"

```

Is it worth it though? You can always pull the entire JSON object if you wanted. Most settings are simple key/value pairs. What do you think?

**Comment by DataWorm** [comment]
Oh damn it, I ignored arrays in purpose cause I expected it to be key-value structure but as you realised it isn't. I see 4 solutions:

1. Instead of using the strings we could return a map of Objects. But then we are back to the case that people have to deal with json again and I think we could just go back to your method then. So I don't like this option.
2. As you said we could just accept it this way since most values aren't arrays and if someone needs to work with arrays, they could still use your other method (or parse the string and then iterate over values).
3. We could make it a bit ugly. Let's assume we have `{ 'foo': { 'bar': ['value1', 'value2', 'value3'] } }`. We could convert it to:
```
'foo.bar' -> '3'  (Number of entries)
'foo.bar.0' -> 'value1'
'foo.bar.1' -> 'value2'
'foo.bar.2' -> 'value3'
```
4. Instead of a map we could return an instance of a new class that works (or inherits) like a map but provides options to retrieve the different Datatypes (like getLong, getString, getStringArray...). That would be like the first solution but the user don't need to work with json classes and conversion.

From my point of view Option 2 and 4 are the best solutions but you can choose! =)

**Comment by robweber** [comment]
I think we're both on the same page, let's just go with number 2. It suits both our needs, if the issue comes up with some 3rd user down the road it can be addressed then. My main use case was the temp profiles, and that's handled with the java object already created. Yours was with the string settings. I'm all for making things as generic as possible but going through the effort here when it's likely it will never bear fruit is kind of a thankless task.

**Pull request merged**
