### PR TITLE
added method to handle print jobs

### PR DESCRIPTION
**Pull request by DataWorm**

### CODE REVIEW

**Comment by robweber** [comment]
Thanks for the contribution! 

Did you have a chance to try any of this yourself? I ran it against a print job I had running. I think I can see what you're after but some of your additions duplicate existing methods, at least from what I can see. 

The getCurrentJob() command isn't doing what you expected. The call actually returns PrinterState, which is duplicated in the getCurrentState() command. Here is the raw JSON output from that call, and then the output of the returned getCurrentState() object:
```
//Octoprint /api/printer/ command
{"text":"Printing","flags":{"error":false,"closedOrError":false,"paused":false,"sdReady":false,"printing":true,"operational":true,"ready":true}}

//Java Lib getCurrentState() command
{"state":{"text":"Printing","flags":{"error":false,"closedOrError":false,"paused":false,"sdReady":false,"printing":true,"operational":true,"ready":true}},"sd":{"ready":false},"temperature":{"tool0":{"target":205.0,"actual":205.0,"offset":0},"bed":{"target":60.0,"actual":59.7,"offset":0}}}
```

Did you want just current information about the currently printing job? You can do that with the JobCommand class. Should look something like: 

```
OctoPrintJob runningJob = jobCommand.getJobDetails();

```

Regarding the other addition, the sendJobCommand() function. There is a method under the /api/printer   REST url for sending [arbitrary printer commands](http://docs.octoprint.org/en/master/api/printer.html#send-an-arbitrary-command-to-the-printer). That takes raw GCODE input though, is that what you were trying to do? The JobState enum wouldn't work for that. If you just want to modify the current job state you can use the JobCommand class again. Simple one would be:

``` 
jobCommand.updateJob(JobState.PAUSE);

```
Let me know if I'm way off base here with what you were trying to accomplish.

**Comment by DataWorm** [comment]
Yeah I was obviously out of my mind. You are right, the features I was looking for were already available. This request could therefore be closed. 
But the methods OctoPrintJob.percentComplete() and getEstimatedPrintTime() return the elementary datatype double instead of the corresponding Double class. The cast to elementary return type results in a NullPointerException when no print job is assigned. elapsedTime() and timeRemaining() already uses the Long class so it works fine.

**Comment by DataWorm** [comment]
Ah and one more point: Does it make sense that elapsedTime() and remainingTime() return Long but getEstimatedPrintTime() returns Double?! I would expect all of them to be in seconds so Long seems to be appropriate.

**Comment by robweber** [comment]
Good points! I'll open an issue to keep track of this. I'll consult the OctoPrint docs for that data model but at the very least they should us the class and not the primitive to make things consistant.

**Pull request closed without merging**
